sudo: required

language: go

services:
- docker

go:
- 1.11.2

install: true

script:
- make

before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  - provider: script
    script: make deploy
    on:
      tags: true
      branch: master
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: tR6/QxAjLIf4cozh8BCnMzfwQuIyE6YTHqymP8Lpx1RsdtmfqI4SkpUXRNLIv4j7VsEuDgZan0eq0ZRbdJIUfG1HfvMU0NzHZLRX2tVmWjyKf1ofi5AiKKzcfjj0o4y4KFUAykhifW92gY5UeNTwuk/PB8oe5P0ELtszyFmXk70/cluh5E6JKBJz1KQad2mXbIJQs9Zc22ZE+gk5WngLZdh9dpg9AyEaG1hntD1D9IXReYfLQSjsTq+hMIO0P5/qcj1T3yKXxOHFnQIMJBx+t9g7LVs0b13z3rpGGE2yAxr15X9QxmxGp8mNfaGG7y6kR207R742PqoRLj8mOgbURxypBav0BC/dvFVVbuDkU8GA1PuLDWKccYzZu59cpOaigePCAjnuy/SmCj0SfYJv2f1Frl9iqOlcGejCekqza26FWOoSCjJUY+0WnZcJ15c7m9KQqZ4b3t5guaqLFKV2U17MaUJRO/zF/xeW5OL7tAgRfkQgkXyeWADrtV0aXEWtoalnDja2kemxvSIrTnKkY+pEyxw+Zyzev+IPFGHugFpZBLyyOsVgnIuZFjxyghyu+wQySmsEXm07TiZfn0rqc1CkOx4x5t5BeA29dEFfg5jqXOnCxtA71MZegbD18E/G6s4pox5Or2vD9OKIOH6REWo5p+GfB2b0BpINwX2+fug=
    file: "$TRAVIS_BUILD_DIR/virtual-ip"
    on:
      tags: true
      repo: darxkies/virtual-ip
      branch: travis
